name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: git config --global core.autocrlf false

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detekt


  build-on-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure git
        run: git config --global core.autocrlf true

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detekt